import { promises } from 'fs'
import { extname, join } from 'path'

const { opendir, stat, writeFile } = promises

async function findMarkdownFiles(contentDir) {
    const dir = await opendir(contentDir);
    const markdownFiles = []
    for await (const dirent of dir) {
        if (dirent.isFile() && extname(dirent.name).toLowerCase() === '.md') {
            const fileName = dirent.name
            const fileStat = await stat(join(contentDir, fileName))
            markdownFiles.push({
                path: fileName,
                created: fileStat.birthtimeMs,
                lastModified: fileStat.mtimeMs,
            })
        }
    }
    return markdownFiles
}

async function writeToc(contentDir, contents) {
    return await writeFile(join(contentDir, 'index.json'), JSON.stringify(contents, null, 2), 'utf-8')
}

async function main(contentDir) {
    const markdownFiles = await findMarkdownFiles(contentDir)
    console.dir(markdownFiles)
    writeToc(contentDir, {
        description: `This file is automatically generated at ${new Date()}`,
        posts: markdownFiles
    })
}

main('./jj-examples/blog/content').catch(console.error)